// Copyright (c) 2026 Rasel Hossen
// Licensed under The Go Engineer License v1.0

// ============================================================================
// Section 06: Backend, APIs & Databases
// Title: gRPC Service Exercise
// Level: Core
// ============================================================================
//
// WHAT YOU'LL LEARN:
//   - How to implement a gRPC server interface in Go.
//   - How to manage context and errors in an RPC environment.
//   - Best practices for service implementation vs. transport.
//
// WHY THIS MATTERS:
//   - Real gRPC work involves implementing the interfaces generated by
//     protoc. This exercise bridges the gap between schema design
//     and server logic.
//
// RUN:
//   go run ./06-backend-db/01-web-and-database/apis/9-grpc-service-exercise
//
// KEY TAKEAWAY:
//   - A gRPC service is just a Go interface implementation with
//     network-aware constraints.
// ============================================================================

package main

import (
	"context"
	"fmt"
	"time"
)

// --- Simulated Generated Code (from .proto) ---
// In a real project, these types would be generated by protoc.

// User (Struct): groups the state used by the user example boundary.
type User struct {
	ID    int32
	Email string
}

// GetUserRequest (Struct): groups the state used by the get user request example boundary.
type GetUserRequest struct {
	ID int32
}

// UserResponse (Struct): groups the state used by the user response example boundary.
type UserResponse struct {
	User *User
}

// UserServiceServer is the interface our implementation must satisfy.
// UserServiceServer (Interface): is the interface our implementation must satisfy.
type UserServiceServer interface {
	GetUser(ctx context.Context, req *GetUserRequest) (*UserResponse, error)
}

// --- Our Implementation ---

// userService (Struct): groups the state used by the user service example boundary.
type userService struct {
	// Simulated database
	users map[int32]*User
}

// userService.GetUser (Method): applies the get user operation to receiver state at a visible boundary.
func (s *userService) GetUser(ctx context.Context, req *GetUserRequest) (*UserResponse, error) {
	// 1. Simulate network latency
	select {
	case <-time.After(100 * time.Millisecond):
	case <-ctx.Done():
		return nil, ctx.Err()
	}

	// 2. Logic
	user, ok := s.users[req.ID]
	if !ok {
		return nil, fmt.Errorf("user not found (ID: %d)", req.ID)
	}

	return &UserResponse{User: user}, nil
}

func main() {
	fmt.Println("=== API.9 gRPC Service ===")
	fmt.Println()

	// 1. Initialize our service
	impl := &userService{
		users: map[int32]*User{
			1: {ID: 1, Email: "alice@example.com"},
			2: {ID: 2, Email: "bob@example.com"},
		},
	}

	// 2. Simulate an incoming RPC call
	fmt.Println("  [RPC] Calling GetUser(ID=1)...")
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()

	resp, err := impl.GetUser(ctx, &GetUserRequest{ID: 1})
	if err != nil {
		fmt.Printf("  [ERROR]: %v\n", err)
	} else {
		fmt.Printf("  [SUCCESS]: Found User %s\n", resp.User.Email)
	}

	// 3. Simulate a missing user
	fmt.Println("\n  [RPC] Calling GetUser(ID=99)...")
	resp, err = impl.GetUser(ctx, &GetUserRequest{ID: 99})
	if err != nil {
		fmt.Printf("  [ERROR]: %v\n", err)
	}

	fmt.Println("\n---------------------------------------------------")
	fmt.Println("NEXT UP: DB.1 -> 06-backend-db/01-web-and-database/databases/1-connecting-to-db")
	fmt.Println("Current: API.9 (grpc-service-exercise)")
	fmt.Println("Previous: API.8 (rest-vs-grpc)")
	fmt.Println("---------------------------------------------------")
}
