// Copyright (c) 2026 Rasel Hossen
// Licensed under The Go Engineer License v1.0

// ============================================================================
// Section 28 Preview: go:generate
// ============================================================================
//
// WHAT YOU'LL LEARN:
//   - The //go:generate directive: embedding tool invocations in source code
//   - Why code generation is preferable to reflection for performance-critical code
//   - Three concrete use cases: mockery, stringer, sqlc
//
// THE PROBLEM:
//   You have a UserRepository interface. Your unit tests need a mock.
//   You can:
//     A) Write the mock by hand (tedious, breaks when the interface changes)
//     B) Use reflect at runtime (slow, loses type safety)
//     C) Generate the mock from the interface definition (fast, type-safe, auto-updates)
//   Option C is go:generate.
//
// HOW IT WORKS:
//   1. Add a //go:generate comment above the interface/type
//   2. Run: go generate ./...
//   3. The tool runs and creates/updates the generated file
//   4. Commit the generated file — it is ordinary Go source code
//
// USAGE:
//   go generate ./...     — run all generators in the module
//   go generate ./pkg/... — run generators in a specific package
//
// ============================================================================

package repository

// UserRepository defines data access for users.
// The mock below is generated by mockery. Run:
//
//go:generate mockery --name=UserRepository --output=../mocks --outpkg=mocks
type UserRepository interface {
	GetByID(id int) (*User, error)
	Create(u *User) (int, error)
	Update(u *User) error
	Delete(id int) error
}

type User struct {
	ID    int
	Email string
	Name  string
}

// ============================================================================
// stringer: generate String() for an enum
// ============================================================================

// Direction is an enum. stringer generates String() for it automatically.
// Run: go generate ./...
//
//go:generate stringer -type=Direction
type Direction int

const (
	North Direction = iota
	South
	East
	West
)

// After running go generate, the tool creates direction_string.go:
//
//  func (d Direction) String() string {
//      switch d {
//      case North: return "North"
//      case South: return "South"
//      case East:  return "East"
//      case West:  return "West"
//      default:    return "Direction(" + strconv.Itoa(int(d)) + ")"
//      }
//  }
//
// This is faster than a manual switch because it is generated once at
// compile time, and the compiler can inline it.

// ============================================================================
// sqlc: generate type-safe database queries
// ============================================================================
//
// sqlc reads your SQL schema and query files and generates Go code.
// Write SQL once; get type-safe functions that match your database schema exactly.
//
// 1. Install: go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
// 2. Create sqlc.yaml:
//      version: "2"
//      sql:
//        - schema: "./schema.sql"
//          queries: "./queries.sql"
//          engine: "postgresql"
//          gen:
//            go:
//              package: "db"
//              out: "./db"
// 3. Write queries.sql:
//      -- name: GetUser :one
//      SELECT id, email, name FROM users WHERE id = $1;
//
//      -- name: CreateUser :one
//      INSERT INTO users (email, name) VALUES ($1, $2) RETURNING id;
// 4. Run: sqlc generate
// 5. Use the generated code:
//      user, err := queries.GetUser(ctx, 42)   // user is *db.User, fully typed
//
//go:generate sqlc generate
